// Typed audit event names (REQ-110). Every mutation and every authentication event appends one
// row; the table refuses updates and deletes, so this list only ever grows.

export const AUDIT_EVENTS = {
  loginSuccess: 'login.success',
  loginFailure: 'login.failure',
  loginThrottled: 'login.throttled',
  loginAborted: 'login.aborted',
  logout: 'session.logout',
  sessionStarted: 'session.started',
  sessionRevoked: 'session.revoked',
  recoveryMinted: 'recovery.minted',
  recoveryClaimed: 'recovery.claimed',
  recoveryUsed: 'recovery.used',
  logoutDelivered: 'logout.delivered',
  logoutFailed: 'logout.failed',
  logoutSlowRevoke: 'logout.slow_revoke',
  accessDenied: 'authz.denied',
  grantCreated: 'grant.created',
  grantChanged: 'grant.changed',
  grantRevoked: 'grant.revoked',
  groupCreated: 'group.created',
  groupUpdated: 'group.updated',
  groupRemoved: 'group.removed',
  groupMembersChanged: 'group.members_changed',
  groupGrantChanged: 'group.grant_changed',
  groupGrantRevoked: 'group.grant_revoked',
  appRegistered: 'app.registered',
  appUpdated: 'app.updated',
  appSecretRotated: 'app.secret_rotated',
  appEnabled: 'app.enabled',
  appDisabled: 'app.disabled',
  appRemoved: 'app.removed',
  keyGenerated: 'key.generated',
  keyPromoted: 'key.promoted',
  keyRetired: 'key.retired',
  ownerClaimed: 'owner.claimed',
  personSuspended: 'person.suspended',
  personReactivated: 'person.reactivated',
  personReset: 'person.reset',
  personKindChanged: 'person.kind_changed',
  inviteCreated: 'invite.created',
  inviteAccepted: 'invite.accepted',
  inviteRevoked: 'invite.revoked',
  deviceTrusted: 'device.trusted',
  deviceRevoked: 'device.revoked',
  profileUpdated: 'person.profile_updated',
  passwordChanged: 'password.changed',
  stepUp: 'auth.step_up',
  settingsChanged: 'settings.changed',
  stateExported: 'state.exported',
  stateImported: 'state.imported',
  seedApplied: 'seed.applied',
  backupCreated: 'backup.created',
  backupFailed: 'backup.failed',
  drillPassed: 'backup.drill_passed',
  drillFailed: 'backup.drill_failed',
  alertSent: 'alert.sent',
  tokenRefreshReused: 'token.refresh_reused',
  mailFailed: 'mail.failed',
  mailTested: 'mail.tested',
  factorAdded: 'factor.added',
  factorRemoved: 'factor.removed',
  devSeedUser: 'dev.seed.user',
  devSeedApp: 'dev.seed.app',
} as const;

export type AuditEventName = (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];

export type AuditTargetType = 'user' | 'app' | 'session' | 'signing_key' | 'grant' | 'group';
