#!/usr/bin/env node
// Writes .env for local development if it does not exist: fresh random secrets, a localhost
// issuer and the Phase 0 dev login. Never overwrites an existing .env.

import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';

const path = new URL('../.env', import.meta.url);
if (existsSync(path)) {
  console.log('.env exists; leaving it alone');
  process.exit(0);
}

const secret = () => randomBytes(32).toString('base64');
writeFileSync(
  path,
  `# Local development only — generated by scripts/dev-env.mjs
ISSUER=http://localhost:3000
INSECURE_HTTP_ISSUER=true
POSTGRES_PASSWORD=d3auth
DATABASE_URL=postgresql://d3auth:d3auth@127.0.0.1:5432/d3auth
KEK=${secret()}
PEPPER=${secret()}
COOKIE_KEYS=${secret()}
OPERATOR_DISPLAY_NAME=Developer
`,
  { mode: 0o600 },
);
console.log('wrote .env with fresh local secrets');
